export interface Person {
  id: string;
  firstName: string;
  lastName: string;
  number?: number;
  position?: string; // e.g. "Setter", "Outside", "Middle", "Opposite", "Libero"
  roleIds?: string[]; // IDs of RoleDefinition entries currently held by this person, e.g. ["role_team_accountant"]
  type: "player" | "coach";
  active?: boolean;
  exemptFromDutyReverse?: boolean;
}

// Alias for Player
export type Player = Person;

export interface FineRule {
  id: string;
  title: string;
  fine?: number; // fallback/summary rate
  fineMatch?: number; // Match rate (kr)
  finePractice?: number; // Practice rate (kr)
  fineSocial?: number; // Social rate (kr)
  category?: string;
  description?: string;
}

export type OccasionType = "Practice" | "Match" | "Social" | "Other";

export type TrialStatus = "requested" | "approved" | "rejected" | "resolved";
export type TrialOutcome = "acquitted" | "guilty" | "transferred";

export interface FineReport {
  id: string;
  playerId: string; // ID of the person (player or coach)
  playerName: string; // Snapshot display name or full name
  ruleIds: string[];
  ruleTitles: string[];
  totalFine: number;
  comment: string;
  reportedBy?: string;
  date: string; // ISO string
  eventContext: OccasionType | string; // "Practice", "Match", "Social", "Other"
  status: "pending" | "approved" | "rejected";
  // Trial ("rettsak") system: a player can contest an approved fine at the next
  // "botfest". Undefined trialStatus = no trial requested.
  trialStatus?: TrialStatus;
  trialRequestedById?: string;
  trialRequestedByName?: string; // snapshot, in case the person is later removed
  trialRequestComment?: string; // grounds for appeal, player-submitted
  trialRequestedAt?: string; // ISO string
  trialDecidedAt?: string; // ISO string, when admin approved/rejected the request
  trialOutcome?: TrialOutcome; // set when the trial is resolved at the botfest
  trialOriginalFine?: number; // snapshot of totalFine before a "guilty" verdict doubles it
  trialOriginalPlayerId?: string; // snapshot of playerId before a "transferred" verdict reassigns it
  trialOriginalPlayerName?: string; // snapshot of playerName before a "transferred" verdict reassigns it
  trialResolvedAt?: string; // ISO string
}



export interface DugnadActivity {
  id: string;
  title: string;
  defaultHours: number;
  pointsPer: number;
  pointsType: "perHour" | "fixed";
  description?: string;
}

// A role a person can hold (e.g. "Team Accountant"), with a fixed point value
// awarded to the person for as long as they hold it. Managed by admin in the
// "Dugnad Rates" tab; assigned to persons from the roster edit modal.
export interface RoleDefinition {
  id: string;
  title: string; // e.g. "Team manager", "Team Accountant", "Social Media Manager"
  points: number; // points awarded to a person for as long as they hold this role
  description?: string;
}

export interface DugnadEntry {
  id: string;
  playerId: string; // player ID only
  playerName: string;
  activityType: string;
  hours: number; // total duty + travel hours
  points: number; // total duty + travel points
  dutyHours?: number;
  dutyPoints?: number;
  hadTravel?: boolean;
  travelHours?: number;
  travelPoints?: number;
  comment?: string;
  date: string; // ISO string
  reportedBy?: string;
  status: "pending" | "approved" | "rejected";
  roleId?: string; // present only on entries auto-generated by assigning a RoleDefinition to a person;
                    // used to find and remove this exact entry again if the role is later revoked
}

export interface TeamSettings {
  teamName: string;
  season: string; // e.g. "26/27"
  finePotPublished: boolean;
  hourlyPointsRate: number;
}

export interface PlayerBackupData extends Person {
  totalFineSum: number;
  totalDugnadHours: number;
  totalDugnadPoints: number;
  fines: FineReport[];
  dugnad: DugnadEntry[];
}

export interface TeamDataBackup {
  _documentation?: {
    title?: string;
    description?: string;
    howToPopulate?: string;
    howToRestore?: string;
  };
  version: string;
  exportedAt: string;
  teamSettings?: Partial<TeamSettings>;
  fineRules?: FineRule[];
  dugnadActivities?: DugnadActivity[];
  roleDefinitions?: RoleDefinition[];
  players: PlayerBackupData[];
  coaches?: Person[];
  unassignedFines?: FineReport[];
  unassignedDugnad?: DugnadEntry[];
}